server:
  port: 8085

logging:
  level:
    '[org.springframework.cloud.gateway]': DEBUG
    '[reactor.netty.http.client]': DEBUG

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    register-with-eureka: true
    healthcheck:
      enabled: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: apigatewayserver
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/auth/**
                    
        - id: products
          uri: lb://PRODUCTS
          predicates:
            - Path=/products/**

        - id: orders
          uri: lb://ORDERS
          predicates:
            - Path=/orders/**
