server:
  port: 8085

logging:
  level:
    "[org.springframework.cloud.gateway]": DEBUG
    "[reactor.netty.http.client]": DEBUG

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    register-with-eureka: true
    healthcheck:
      enabled: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: apigatewayserver
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**

        - id: products
          uri: lb://products
          predicates:
            - Path=/products/**

        - id: orders
          uri: lb://orders
          predicates:
            - Path=/orders/**
