services:
  auth-service:
    container_name: auth-service
    build:
      context: ./business/auth
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      JWT_SECRET: "2f29cefef678f48e80a1414e58f885288fd44747fa8c708485a3c8a0375a68da"
      DATASOURCE_URL: "jdbc:mysql://mysql:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
      DATASOURCE_USERNAME: "root"
      DATASOURCE_PASSWORD: "root"
      EUREKA_SERVER: "http://eurekaserver:8761/eureka"
    depends_on:
      - mysql
      - eurekaserver
    networks:
      - backend-network

  orders:
    container_name: orders
    build:
      context: ./business/orders
      dockerfile: dockerfile
    ports:
      - "3002:3002"
    environment:
      DATASOURCE_URL: "jdbc:mysql://mysql:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
      DATASOURCE_USERNAME: "root"
      DATASOURCE_PASSWORD: "root"
      EUREKA_SERVER: "http://eurekaserver:8761/eureka"

    depends_on:
      - mysql
    networks:
      - backend-network

  products:
    container_name: products
    build:
      context: ./business/products
      dockerfile: dockerfile
    ports:
      - "3001:3001"
    environment:
      DATASOURCE_URL: "jdbc:mysql://mysql:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
      DATASOURCE_USERNAME: "root"
      DATASOURCE_PASSWORD: "root"
      EUREKA_SERVER: "http://eurekaserver:8761/eureka"
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: "asupersecretpassword"

    depends_on:
      - mysql
    networks:
      - backend-network

  eurekaserver:
    container_name: eurekaserver
    build:
      context: ./infrastructure/eurekaserver
      dockerfile: dockerfile
    ports:
      - "8761:8761"
    networks:
      - backend-network

  apigateway:
    container_name: apigateway
    build:
      context: ./infrastructure/apigatewayserver
      dockerfile: dockerfile
    ports:
      - "8085:8085"
    environment:
      EUREKA_SERVER: "http://eurekaserver:8761/eureka"
    depends_on:
      - eurekaserver
    networks:
      - backend-network

  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3344:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - backend-network

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    environment:
      ELASTIC_PASSWORD: asupersecretpassword
      xpack.security.enabled: "true"
      discovery.type: "single-node"

    ports:
      - "9200:9200"
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    networks:
      - backend-network

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.17.2
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_SERVICE_TOKEN: AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbjpuQ21DbXo0OFJMS2Zsd1lncHRnc2dR
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - backend-network

volumes:
  mysql_data:
  es_data:

networks:
  backend-network:
    driver: bridge
