INSERT INTO marcas (id, descripcion) VALUES ('1', 'Cremin PLC');
INSERT INTO marcas (id, descripcion) VALUES ('2', 'Predovic-Hegmann');
INSERT INTO marcas (id, descripcion) VALUES ('3', 'Tremblay-Hammes');
INSERT INTO marcas (id, descripcion) VALUES ('4', 'Gulgowski-Shanahan');
INSERT INTO marcas (id, descripcion) VALUES ('5', 'Herzog, Larkin and Friesen');
INSERT INTO marcas (id, descripcion) VALUES ('6', 'Weber-Lemke');
INSERT INTO marcas (id, descripcion) VALUES ('7', 'Thiel, Donnelly and Gerhold');
INSERT INTO marcas (id, descripcion) VALUES ('8', 'Kshlerin PLC');
INSERT INTO marcas (id, descripcion) VALUES ('9', 'Jaskolski Inc');
INSERT INTO marcas (id, descripcion) VALUES ('10', 'Orn-Terry');
INSERT INTO marcas (id, descripcion) VALUES ('11', 'Hayes Inc');
INSERT INTO marcas (id, descripcion) VALUES ('12', 'McKenzie LLC');
INSERT INTO marcas (id, descripcion) VALUES ('13', 'Powlowski and Sons');
INSERT INTO marcas (id, descripcion) VALUES ('14', 'Fadel-Swaniawski');
INSERT INTO marcas (id, descripcion) VALUES ('15', 'Carter LLC');
INSERT INTO marcas (id, descripcion) VALUES ('16', 'Walker, Rogahn and Pacocha');
INSERT INTO marcas (id, descripcion) VALUES ('17', 'McCullough and Sons');
INSERT INTO marcas (id, descripcion) VALUES ('18', 'Kautzer, Rodriguez and Mitchell');
INSERT INTO marcas (id, descripcion) VALUES ('19', 'Runolfsdottir-Kertzmann');
INSERT INTO marcas (id, descripcion) VALUES ('20', 'Anderson-Greenholt');
INSERT INTO marcas (id, descripcion) VALUES ('21', 'Baumbach Group');
INSERT INTO marcas (id, descripcion) VALUES ('22', 'Rosenbaum, Stehr and Leffler');
INSERT INTO marcas (id, descripcion) VALUES ('23', 'Mills, Bergstrom and Grimes');
INSERT INTO marcas (id, descripcion) VALUES ('24', 'Kulas LLC');
INSERT INTO marcas (id, descripcion) VALUES ('25', 'Conroy-Satterfield');
INSERT INTO marcas (id, descripcion) VALUES ('26', 'Prohaska-Witting');
INSERT INTO marcas (id, descripcion) VALUES ('27', 'Kuhic, Collins and Kutch');
INSERT INTO marcas (id, descripcion) VALUES ('28', 'Pouros PLC');
INSERT INTO marcas (id, descripcion) VALUES ('29', 'Powlowski, Schamberger and Roob');
INSERT INTO marcas (id, descripcion) VALUES ('30', 'Jones-White');