# Usa una imagen oficial de OpenJDK como base
FROM openjdk:17-jdk-slim

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo JAR de la aplicación (debe estar compilado previamente)
COPY target/*.jar app.jar

# Expone el puerto configurado en la aplicación
EXPOSE 8083

# Comando de ejecución de la aplicación
CMD ["java", "-jar", "app.jar"]
