# Usar una imagen base de Java
FROM openjdk:17-jdk-slim

# Configurar directorio de trabajo
WORKDIR /app

# Copiar el archivo JAR generado
COPY target/*.jar app.jar

# Exponer el puerto del API Gateway
EXPOSE 8080

# Establecer variables de entorno para la conexión a MySQL
ENV MYSQL_HOST=mysql
ENV MYSQL_PORT=3306
ENV MYSQL_DATABASE=mydb
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=root

# Ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"] 